######################################################################
# Automatically generated by qmake (2.01a) Thu Oct 21 11:46:35 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h ../wrapper-build-desktop/ui_mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
